{% set name = "ESMValTool" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 099160392048f7ccddb420790e0529ce1ee8b795962be51ebd09e78b8ea38cac

build:
  number: 1

outputs:
  - name: esmvaltool-python
    build:
      noarch: python
      entry_points:
        - mip_convert_setup = esmvaltool.cmorizers.mip_convert.esmvt_mipconv_setup:main
        - nclcodestyle = esmvaltool.utils.nclcodestyle.nclcodestyle:_main
        - test_recipe = esmvaltool.utils.testing.recipe_settings.install_expand_run:main
        - recipe_filler = esmvaltool.utils.recipe_filler:run
    script: build_python.bat  # [win]
    script: build_python.sh  # [not win]
    requirements:
      build:
        - python >=3.9,<3.12
        - pip !=21.3
      host:
        - python >=3.9,<3.12
        - setuptools_scm
        - pip !=21.3
      run:
        - aiohttp
        - cartopy <0.24  # https://github.com/ESMValGroup/ESMValTool/issues/3767
        - cdo >=2.3.0
        - cdsapi
        - cf-units
        - cftime
        - cmocean
        - curl <8.10  # https://github.com/ESMValGroup/ESMValTool/pull/3755
        - cython
        - dask
        - distributed
        - ecmwf-api-client
        - eofs
        - esmpy !=8.1.0,<8.6.0  # https://github.com/SciTools-incubator/iris-esmf-regrid/pull/342#issuecomment-2092921514
        - esmvalcore 2.11.*
        - fiona
        - fire
        - fsspec
        - gdal
        - importlib_metadata <8  # required for Python < 3.10
        - iris >=3.6.1
        - iris-esmf-regrid >=0.7.0
        - jinja2
        - joblib
        - lime
        - mapgenerator >=1.0.5
        - matplotlib-base <3.9.0
        - natsort
        - nc-time-axis
        - netCDF4
        - numba
        - numpy !=1.24.3,<2.0.0  # severe masking bug, avoid pulling 2.0.0
        - openpyxl
        - packaging
        - pandas <2.2.0 # github.com/ESMValGroup/ESMValCore/pull/2305 and avoid any new Pandas release
        - progressbar2
        - prov
        - psyplot
        - psy-maps
        - psy-reg
        - psy-simple
        - pyproj >=2.1
        - pys2index  # only from conda-forge
        - python >=3.9,<3.12
        - python-cdo
        - python-dateutil
        - pyyaml
        - rasterio
        - requests
        - ruamel.yaml
        - scikit-image
        - scikit-learn >=1.4.0  # github.com/ESMValGroup/ESMValTool/issues/3504
        - scipy
        - seaborn
        - seawater
        - shapely >=2
        - xarray >=0.12.0
        - xesmf >=0.7.1
        - xgboost >1.6.1  # github.com/ESMValGroup/ESMValTool/issues/2779
        - xlsxwriter
        - zarr
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - flake8
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-mock
        - pytest-xdist
      imports:
        - esmvaltool
      commands:
        - pytest -n 2 --ignore="run_test.py" --ignore="tests/unit/documentation/" -k "not ([diagnostic.R] or [diagnostic.jl] or [diagnostic.ncl] or test_r_lint)"
        - esmvaltool --help
        - esmvaltool data --help
        - nclcodestyle --help
        - esmvaltool colortables --help
        - test_recipe --help

  # - name: esmvaltool-julia
  #   build:
  #     noarch: generic
  #     post-link: install-julia-deps
  #   requirements:
  #     run:
  #       - esmvaltool-python

  - name: esmvaltool-ncl
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - ncl >=6.6
        - cdo >=2.3.0
        - imagemagick
        - nco
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - flake8
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-mock
        - pytest-xdist
      commands:
        - pytest -n 2 -k "[diagnostic.ncl]"

  - name: esmvaltool-r
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - nco
        - cdo >=2.3.0
        - r-base >=3.5,<4.3.0
        - r-abind
        - r-akima
        - r-climdex.pcic
        - r-climprojdiags
        - r-docopt
        - r-dotcall64
        - r-functional
        - r-ggplot2
        - r-gridextra
        - r-lintr
        - r-logging
        - r-mapproj
        - r-maps
        - r-multiapply
        - r-ncdf4
        - r-ncdf4.helpers
        - r-pcict
        - r-plyr
        - r-rcolorbrewer
        - r-rcpp
        - r-s2dverification
        - r-snow
        - r-spei
        - r-styler
        - r-udunits2
        - r-yaml
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - flake8
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-mock
        - pytest-xdist
      commands:
        - pytest -n 2 -k "[diagnostic.R] or test_r_lint"

  - name: esmvaltool
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9,<3.12
      run:
        - python >=3.9,<3.12
        # - {{ pin_subpackage('esmvaltool-julia', exact=True) }}
        - {{ pin_subpackage('esmvaltool-ncl', exact=True) }}
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - {{ pin_subpackage('esmvaltool-r', exact=True) }}
    test:
      imports:
        - esmvaltool
      commands:
        - esmvaltool --help
        - esmvaltool recipes list
        - esmvaltool version
        - esmvaltool data --help
        - nclcodestyle --help
        - esmvaltool colortables --help
        - test_recipe --help

about:
  home: https://www.esmvaltool.org
  license: Apache-2.0
  license_file: LICENSE
  summary: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.
  description: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.

extra:
  recipe-maintainers:
    - bettina-gier
    - ehogan
    - remi-kazeroni
    - sloosvel
    - schlunma
    - zklaus
    - valeriupredoi
    - nielsdrost
    - bouweandela
