{% set name = "ESMValTool" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 397f0e94d0f75112d159dad4e7fb6a16594e07749590fcef163eb99f10b10f1b

build:
  number: 2

outputs:
  - name: esmvaltool-python
    build:
      noarch: python
      entry_points:
        - mip_convert_setup = esmvaltool.cmorizers.mip_convert.esmvt_mipconv_setup:main
        - nclcodestyle = esmvaltool.utils.nclcodestyle.nclcodestyle:_main
        - test_recipe = esmvaltool.utils.testing.recipe_settings.install_expand_run:main
        - recipe_filler = esmvaltool.utils.recipe_filler:run
    script: build_python.bat  # [win]
    script: build_python.sh  # [not win]
    requirements:
      build:
        - python >=3.8
        - pip !=21.3
      host:
        - python >=3.8
        - setuptools_scm
        - pip !=21.3
      run:
        - cartopy
        - cdo >=1.9.7
        - cdsapi
        - cf-units >=3.0.0,<3.1.0,!=3.0.1.post0
        - cftime
        - cmocean
        - cython
        - dask
        - ecmwf-api-client
        - eofs
        - esmpy <8.4  # github.com/ESMValGroup/ESMValCore/issues/1870
        - esmvalcore 2.7.*
        - fiona
        - fire
        - gdal
        - iris >=3.1.0
        - iris-esmf-regrid
        - jinja2
        - joblib
        - lime
        - mapgenerator >=1.0.5
        - matplotlib-base <3.6.0
        - natsort
        - nc-time-axis
        - netCDF4
        - numpy
        - openpyxl
        - pandas
        - progressbar2
        - prov
        - psy-maps
        - psy-reg
        - psy-simple
        - psyplot
        - pyproj >=2.1
        - python >=3.8
        - python-cdo
        - python-dateutil
        - pyyaml
        - rasterio  # replaces pynio
        - requests
        - ruamel.yaml
        - scikit-image
        # remove this pin at release; this uses older, deprecated code
        - scikit-learn <1.2.0  # github.com/ESMValGroup/ESMValTool/pull/2961
        - scipy
        - seaborn
        - seawater
        - shapely <2.0.0  # github.com/ESMValGroup/ESMValTool/issues/2992
        - xarray >=0.12.0
        - xesmf =0.3.0
        - xgboost >1.6.1
        - xlsxwriter
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - flake8 <4
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-flake8 >=1.0.6
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-xdist
      imports:
        - esmvaltool
      commands:
        - pytest -n 2 --ignore="run_test.py" --ignore="tests/unit/documentation/" -k "not ([diagnostic.R] or [diagnostic.jl] or [diagnostic.ncl] or test_r_lint)"
        - esmvaltool --help
        - esmvaltool data --help
        - nclcodestyle --help
        - esmvaltool colortables --help
        - test_recipe --help

  # - name: esmvaltool-julia
  #   build:
  #     noarch: generic
  #     post-link: install-julia-deps
  #   requirements:
  #     run:
  #       - esmvaltool-python

  - name: esmvaltool-ncl
    build:
      noarch: generic
    requirements:
      run:
        - cdo >=1.9.7
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - imagemagick
        - ncl >=6.6
        - nco
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - flake8 <4
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-flake8 >=1.0.6
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-xdist
      commands:
        - pytest -n 2 -k "[diagnostic.ncl]"

  - name: esmvaltool-r
    build:
      noarch: generic
    requirements:
      run:
        - cdo >=1.9.7
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - nco
        - r-base >=3.5
        - r-abind
        - r-akima <=0.6-2.3
        - r-climdex.pcic
        - r-climprojdiags
        - r-docopt
        - r-dotcall64
        - r-functional
        - r-ggplot2
        - r-gridextra
        - r-lintr
        - r-logging
        - r-mapproj
        - r-maps
        - r-multiapply
        - r-ncdf4
        - r-ncdf4.helpers
        - r-pcict
        - r-plyr
        - r-rcolorbrewer
        - r-rcpp
        - r-s2dverification
        - r-snow
        - r-spei
        - r-styler
        - r-udunits2
        - r-yaml
    test:
      source_files:
        - tests
        - setup.cfg
      requires:
        - flake8 <4
        - pytest >=3.9,!=6.0.0rc1,!=6.0.0
        - pytest-cov
        - pytest-env
        - pytest-flake8 >=1.0.6
        - pytest-html !=2.1.0
        - pytest-metadata >=1.5.1
        - pytest-xdist
      commands:
        - pytest -n 2 -k "[diagnostic.R] or test_r_lint"

  - name: esmvaltool
    build:
      noarch: python
    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        # - {{ pin_subpackage('esmvaltool-julia', exact=True) }}
        - {{ pin_subpackage('esmvaltool-ncl', exact=True) }}
        - {{ pin_subpackage('esmvaltool-python', exact=True) }}
        - {{ pin_subpackage('esmvaltool-r', exact=True) }}
    test:
      imports:
        - esmvaltool
      commands:
        - esmvaltool --help
        - esmvaltool recipes list
        - esmvaltool version
        - esmvaltool data --help
        - nclcodestyle --help
        - esmvaltool colortables --help
        - test_recipe --help

about:
  home: https://www.esmvaltool.org
  license: Apache-2.0
  license_file: LICENSE
  summary: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.
  description: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.

extra:
  recipe-maintainers:
    - remi-kazeroni
    - sloosvel
    - schlunma
    - zklaus
    - valeriupredoi
    - nielsdrost
    - bouweandela
