schema_version: 1

context:
  name: ESMValTool
  version: 2.13.0
  python_min: 3.11

recipe:
  name: ${{ name|lower }}-suite
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name|lower }}-${{ version }}.tar.gz
  sha256: 92d4eac21f594131539b0749c6362f2328d72b70b18e02a4b2b8fe0ef7dea9e5
  patches:
    - 0001-Unpin-ipython.patch

build:
  number: 2

outputs:
  - package:
      name: esmvaltool-python
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
      python:
        entry_points:
          - nclcodestyle = esmvaltool.utils.nclcodestyle.nclcodestyle:_main
    requirements:
      build:
        - pip !=21.3
        - python ${{ python_min }}.*
      host:
        - pip !=21.3
        - python ${{ python_min }}.*
        - setuptools
        - setuptools_scm
      run:
        - aiohttp
        - arviz
        - cartopy
        - cdo >=2.3.0
        - cdsapi
        - cf-units
        - cfgrib
        - cftime
        - cmocean
        - cython
        - dask !=2024.8.0
        - distributed
        - ecmwf-api-client
        - eofs
        - esmpy
        - esmvalcore 2.13.*
        - fiona
        - fire
        - fsspec
        - gdal >=3.9.0
        - imagehash
        - ipython
        - iris >=3.11
        - iris-esmf-regrid >=0.10.0
        - jinja2
        - joblib
        - lime
        - mapgenerator >=1.0.5
        - matplotlib-base
        - natsort
        - nc-time-axis
        - netCDF4
        - numba
        - numpy !=1.24.3 # severe masking bug, avoid pulling 2.0.0
        - openpyxl
        - packaging
        - pandas
        - progressbar2
        - prov
        - pyproj >=2.1
        - pys2index >=0.1.5 # only from conda-forge; 0.1.4 broken
        - python >=${{ python_min }}
        - python-cdo
        - python-dateutil
        - pyyaml
        - rasterio >=1.3.10
        - requests
        - ruamel.yaml
        - scikit-image
        - scikit-learn >=1.4.0 # github.com/ESMValGroup/ESMValTool/issues/3504
        - scipy
        - seaborn
        - seawater
        - shapely >=2.0.2
        - xarray >=0.12.0
        - xesmf >=0.7.1
        - xgboost >1.6.1 # github.com/ESMValGroup/ESMValTool/issues/2779
        - xlsxwriter
        - zarr
    tests:
      - python:
          imports:
            - esmvaltool
          pip_check: true
          python_version: ${{ python_min }}.*
      - files:
          source:
            - tests
            - pyproject.toml
        requirements:
          run:
            - pytest >=3.9,!=6.0.0rc1,!=6.0.0
            - pytest-cov
            - pytest-env
            - pytest-html !=2.1.0
            - pytest-metadata >=1.5.1
            - pytest-mock
            - pytest-xdist
            - python ${{ python_min }}.*
        script:
          - pytest -n 2 --ignore="run_test.py" --ignore="tests/unit/documentation/" -k "not ([diagnostic.R] or [diagnostic.ncl] or test_r_lint)"
          - esmvaltool --help
          - esmvaltool data --help
          - nclcodestyle --help
          - esmvaltool colortables --help
  - package:
      name: esmvaltool-ncl
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage('esmvaltool-python', exact=True) }}
        - ncl >=6.6.2
        - cdo
        - imagemagick
        - nco
    tests:
      - files:
          source:
            - tests
            - setup.cfg
        requirements:
          run:
            - pytest >=3.9,!=6.0.0rc1,!=6.0.0
            - pytest-cov
            - pytest-env
            - pytest-html !=2.1.0
            - pytest-metadata >=1.5.1
            - pytest-mock
            - pytest-xdist
        script:
          - pytest -n 2 -k "[diagnostic.ncl]"
  - package:
      name: esmvaltool-r
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage('esmvaltool-python', exact=True) }}
        - nco
        - cdo
        - r-base >=3.5
        - r-abind
        - r-akima
        - r-climdex.pcic
        - r-climprojdiags
        - r-docopt
        - r-dotcall64
        - r-functional
        - r-ggplot2
        - r-git2r # dependency of r-lintr
        - r-gridextra
        - r-lintr ==3.1.2
        - r-logging
        - r-mapproj
        - r-maps
        - r-multiapply
        - r-ncdf4
        - r-ncdf4.helpers
        - r-pcict
        - r-plyr
        - r-rcolorbrewer
        - r-rcpp
        - r-s2dverification
        - r-snow
        - r-spei
        - r-styler ==1.10.3
        - r-udunits2
        - r-yaml
    tests:
      - files:
          source:
            - tests
            - setup.cfg
        requirements:
          run:
            - pytest >=3.9,!=6.0.0rc1,!=6.0.0
            - pytest-cov
            - pytest-env
            - pytest-html !=2.1.0
            - pytest-metadata >=1.5.1
            - pytest-mock
            - pytest-xdist
        script:
          - pytest -n 2 -k "[diagnostic.R] or test_r_lint"
  - package:
      name: esmvaltool
    build:
      noarch: python
    requirements:
      host:
        - python ${{ python_min }}.*
      run:
        - ${{ pin_subpackage('esmvaltool-ncl', exact=True) }}
        - ${{ pin_subpackage('esmvaltool-python', exact=True) }}
        - ${{ pin_subpackage('esmvaltool-r', exact=True) }}
        - python >=${{ python_min }}
    tests:
      - python:
          imports:
            - esmvaltool
          pip_check: true
          python_version: ${{ python_min }}.*
      - requirements:
          run:
            - python ${{ python_min }}.*
        script:
          - esmvaltool --help
          - esmvaltool recipes list
          - esmvaltool version
          - esmvaltool data --help
          - nclcodestyle --help
          - esmvaltool colortables --help

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.
  description: A community diagnostic and performance metrics tool for routine evaluation of Earth system models in CMIP.
  homepage: https://www.esmvaltool.org

extra:
  recipe-maintainers:
    - jlenh
    - bettina-gier
    - ehogan
    - remi-kazeroni
    - sloosvel
    - schlunma
    - zklaus
    - valeriupredoi
    - nielsdrost
    - bouweandela
    - jlenh
